[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "pyo3_stub_gen_testing_pure"
requires-python = ">=3.9"

[project.optional-dependencies]
test = ["pytest", "pyright"]
