[package]
name = "empty_super_module"
edition.workspace = true
version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger.workspace = true
pyo3-stub-gen = { path = "../../pyo3-stub-gen" }
pyo3.workspace = true

[[bin]]
name = "stub_gen"
doc = false
