[project]
name = "pure"
version = "0.1"
requires-python = ">=3.10"

[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.pyrefly]
project-excludes = ["**/type_error_cases/*.py"]

[tool.pyright]
ignore = ["**/type_error_cases/*.py"]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/*.rs" }]
