name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC token exchange

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: cargo publish
        run: |
          cargo publish -p pyo3-stub-gen-derive
          cargo publish -p pyo3-stub-gen
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  next_version:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump version
        run: |
          cargo set-version --bump patch
          echo "NEW_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "Start developing ${{ env.NEW_VERSION }}"
          branch: "rust-version-update/${{ env.NEW_VERSION }}"
          base: "main"
